version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    volumes:
      - .:/usr/share/nginx/html
    links:
      - db

  db:
    image: mariadb:10.3
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=semhora
